#!/bin/sh
ROOT=`dirname $0`
echo $ROOT

export GOOGLE_APPLICATION_CREDENTIALS=${ROOT}/NHLAGS-e8b3911072d5.json
Sheet_URL=$1
GS_Title=$2
File_Base=$3

echo ${GOOGLE_APPLICATION_CREDENTIALS}

${ROOT}/gs_collab_sheet.py "$Sheet_URL" \
  "$GS_Title" $File_Base.pdf

${ROOT}/gs_collab_sheet.py "$Sheet_URL" \
    "$GS_Title" $File_Base"-y".pdf --gold
